### ISSUE TITLE
Kassandra needs to consume 0.12 of BlueSSLService

### ISSUE THREAD

**Issue by alblue** [IBM-Swift/Kassandra#33]
Currently depending on Kassandra.git and Kitura.git causes a swift package build failure because of a conflicting dependency of BlueSSLService. The solution would be to bump up the dependency of BlueSSLService to 0.12, or change the dependency to `.Package(url: "https://github.com/IBM-Swift/BlueSSLService.git", versions:Version(majorVersion, 11, 0)..<Version(majorVersion, .max, .max))` to allow automated future dependencies to be considered available (providing that he API of BlueSSLService is considered stable)

**Comment by rfdickerson** [comment]
Thanks for the request, I think this is resolved now now that we updated the dependencies.
